
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkinsons-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parkinsons-app
  template:
    metadata:
      labels:
        app: parkinsons-app
    spec:
      containers:
      - name: parkinsons-container
        image: parkinsons-diagnosis:latest
        ports:
        - containerPort: 5000
